import type { Catalog } from '@world-map/core';

export const catalog: Catalog = {
  countries: [
    { code: 'AF', name: 'Afghanistan' },
    { code: 'AO', name: 'Angola' },
    { code: 'AL', name: 'Albania' },
    { code: 'AE', name: 'United Arab Emirates' },
    { code: 'AR', name: 'Argentina' },
    { code: 'AM', name: 'Armenia' },
    { code: 'AU', name: 'Australia' },
    { code: 'AT', name: 'Austria' },
    { code: 'AZ', name: 'Azerbaijan' },
    { code: 'BI', name: 'Burundi' },
    { code: 'BE', name: 'Belgium' },
    { code: 'BJ', name: 'Benin' },
    { code: 'BF', name: 'Burkina Faso' },
    { code: 'BD', name: 'Bangladesh' },
    { code: 'BG', name: 'Bulgaria' },
    { code: 'BA', name: 'Bosnia and Herzegovina' },
    { code: 'BY', name: 'Belarus' },
    { code: 'BZ', name: 'Belize' },
    { code: 'BO', name: 'Bolivia' },
    { code: 'BR', name: 'Brazil' },
    { code: 'BN', name: 'Brunei Darussalam' },
    { code: 'BT', name: 'Bhutan' },
    { code: 'BW', name: 'Botswana' },
    { code: 'CF', name: 'Central African Republic' },
    { code: 'CA', name: 'Canada' },
    { code: 'CH', name: 'Switzerland' },
    { code: 'CN', name: 'China' },
    { code: 'CI', name: "C\u00f4te d'Ivoire" },
    { code: 'CM', name: 'Cameroon' },
    { code: 'CD', name: 'Democratic Republic of the Congo' },
    { code: 'CG', name: 'Republic of Congo' },
    { code: 'CO', name: 'Colombia' },
    { code: 'CR', name: 'Costa Rica' },
    { code: 'CU', name: 'Cuba' },
    { code: 'CZ', name: 'Czech Republic' },
    { code: 'DK', name: 'Denmark' },
    { code: 'DJ', name: 'Djibouti' },
    { code: 'DO', name: 'Dominican Republic' },
    { code: 'DE', name: 'Germany' },
    { code: 'DZ', name: 'Algeria' },
    { code: 'EC', name: 'Ecuador' },
    { code: 'EG', name: 'Egypt' },
    { code: 'ER', name: 'Eritrea' },
    { code: 'EE', name: 'Estonia' },
    { code: 'ET', name: 'Ethiopia' },
    { code: 'FI', name: 'Finland' },
    { code: 'GA', name: 'Gabon' },
    { code: 'GB', name: 'United Kingdom' },
    { code: 'GE', name: 'Georgia' },
    { code: 'GH', name: 'Ghana' },
    { code: 'GN', name: 'Guinea' },
    { code: 'GM', name: 'The Gambia' },
    { code: 'GW', name: 'Guinea-Bissau' },
    { code: 'GQ', name: 'Equatorial Guinea' },
    { code: 'GR', name: 'Greece' },
    { code: 'GL', name: 'Greenland' },
    { code: 'GT', name: 'Guatemala' },
    { code: 'GY', name: 'Guyana' },
    { code: 'HN', name: 'Honduras' },
    { code: 'HR', name: 'Croatia' },
    { code: 'HT', name: 'Haiti' },
    { code: 'HU', name: 'Hungary' },
    { code: 'ID', name: 'Indonesia' },
    { code: 'IN', name: 'India' },
    { code: 'IE', name: 'Ireland' },
    { code: 'IR', name: 'Iran' },
    { code: 'IQ', name: 'Iraq' },
    { code: 'IS', name: 'Iceland' },
    { code: 'IL', name: 'Israel' },
    { code: 'IT', name: 'Italy' },
    { code: 'JM', name: 'Jamaica' },
    { code: 'JO', name: 'Jordan' },
    { code: 'JP', name: 'Japan' },
    { code: 'KZ', name: 'Kazakhstan' },
    { code: 'KE', name: 'Kenya' },
    { code: 'KG', name: 'Kyrgyzstan' },
    { code: 'KH', name: 'Cambodia' },
    { code: 'KR', name: 'Republic of Korea' },
    { code: 'KW', name: 'Kuwait' },
    { code: 'LA', name: 'Lao PDR' },
    { code: 'LB', name: 'Lebanon' },
    { code: 'LR', name: 'Liberia' },
    { code: 'LY', name: 'Libya' },
    { code: 'LK', name: 'Sri Lanka' },
    { code: 'LS', name: 'Lesotho' },
    { code: 'LT', name: 'Lithuania' },
    { code: 'LU', name: 'Luxembourg' },
    { code: 'LV', name: 'Latvia' },
    { code: 'MA', name: 'Morocco' },
    { code: 'MD', name: 'Moldova' },
    { code: 'MG', name: 'Madagascar' },
    { code: 'MX', name: 'Mexico' },
    { code: 'MK', name: 'Macedonia' },
    { code: 'ML', name: 'Mali' },
    { code: 'MM', name: 'Myanmar' },
    { code: 'ME', name: 'Montenegro' },
    { code: 'MN', name: 'Mongolia' },
    { code: 'MZ', name: 'Mozambique' },
    { code: 'MR', name: 'Mauritania' },
    { code: 'MW', name: 'Malawi' },
    { code: 'MY', name: 'Malaysia' },
    { code: 'NA', name: 'Namibia' },
    { code: 'NE', name: 'Niger' },
    { code: 'NG', name: 'Nigeria' },
    { code: 'NI', name: 'Nicaragua' },
    { code: 'NO', name: 'Norway' },
    { code: 'NP', name: 'Nepal' },
    { code: 'OM', name: 'Oman' },
    { code: 'PK', name: 'Pakistan' },
    { code: 'PA', name: 'Panama' },
    { code: 'PE', name: 'Peru' },
    { code: 'PH', name: 'Philippines' },
    { code: 'PG', name: 'Papua New Guinea' },
    { code: 'PL', name: 'Poland' },
    { code: 'KP', name: 'Dem. Rep. Korea' },
    { code: 'PY', name: 'Paraguay' },
    { code: 'PS', name: 'Palestine' },
    { code: 'QA', name: 'Qatar' },
    { code: 'RO', name: 'Romania' },
    { code: 'RW', name: 'Rwanda' },
    { code: 'EH', name: 'Western Sahara' },
    { code: 'SA', name: 'Saudi Arabia' },
    { code: 'SD', name: 'Sudan' },
    { code: 'SS', name: 'South Sudan' },
    { code: 'SN', name: 'Senegal' },
    { code: 'SL', name: 'Sierra Leone' },
    { code: 'SV', name: 'El Salvador' },
    { code: 'RS', name: 'Serbia' },
    { code: 'SR', name: 'Suriname' },
    { code: 'SK', name: 'Slovakia' },
    { code: 'SI', name: 'Slovenia' },
    { code: 'SE', name: 'Sweden' },
    { code: 'SZ', name: 'Swaziland' },
    { code: 'SY', name: 'Syria' },
    { code: 'TD', name: 'Chad' },
    { code: 'TG', name: 'Togo' },
    { code: 'TH', name: 'Thailand' },
    { code: 'TJ', name: 'Tajikistan' },
    { code: 'TM', name: 'Turkmenistan' },
    { code: 'TL', name: 'Timor-Leste' },
    { code: 'TN', name: 'Tunisia' },
    { code: 'TR', name: 'Turkey' },
    { code: 'TW', name: 'Taiwan' },
    { code: 'TZ', name: 'Tanzania' },
    { code: 'UG', name: 'Uganda' },
    { code: 'UA', name: 'Ukraine' },
    { code: 'UY', name: 'Uruguay' },
    { code: 'UZ', name: 'Uzbekistan' },
    { code: 'VE', name: 'Venezuela' },
    { code: 'VN', name: 'Vietnam' },
    { code: 'YE', name: 'Yemen' },
    { code: 'ZM', name: 'Zambia' },
    { code: 'ZW', name: 'Zimbabwe' },
    { code: 'SO', name: 'Somalia' },
    { code: 'XK', name: 'Kosovo' },
    { code: 'ZA', name: 'South Africa' },
    { code: 'NZ', name: 'New Zealand' },
    { code: 'CL', name: 'Chile' },
    { code: 'NL', name: 'Netherlands' },
    { code: 'PT', name: 'Portugal' },
    { code: 'RU', name: 'Russian Federation' },
    { code: 'ES', name: 'Spain' },
    { code: 'FR', name: 'France' },
    { code: 'US', name: 'United States' },
    { code: 'GF', name: 'French Guiana' },
    { code: 'CY', name: 'Cyprus' },
    { code: 'MT', name: 'Malta' },
  ],
  regions: [
    {
      id: 'nordics',
      name: 'Nordics',
      memberCodes: ['FI', 'SE', 'IS', 'NO', 'DK'],
    },
    {
      id: 'eu',
      name: 'European Union',
      memberCodes: [
        'AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE',
        'FI', 'FR', 'DE', 'GR', 'HU', 'IE', 'IT', 'LV',
        'LT', 'LU', 'MT', 'NL', 'PL', 'PT', 'RO', 'SK',
        'SI', 'ES', 'SE',
      ],
    },
  ],
};
